defaults:
  - override hydra/launcher: joblib
env_name: CartPole-v1
batch_size: 1024
training_steps: 200000
learning_rate: 0.01
width: 8
lamb: 0.0
seed: 0

# Network-specific parameters
network:
  method: "KAN"
  hidden_layers: [8]
  grid: 5
  k: 3
  bias_trainable: false
  sp_trainable: false
  sb_trainable: false