defaults:
  - override hydra/launcher: joblib
env_name: CartPole-v1
batch_size: 128
num_minibatches: 4
training_steps: 500000
log_interval: 1000
learning_rate: 2.5e-4
width: 8
grid: 5
lamb: 0.0
method: "MLP" 
seed: 0
# PPO specific parameters
gamma: 0.99
gae_lambda: 0.95
anneal_lr: True
update_epochs: 4
clip_coef: 0.2
clip_vloss: True
norm_adv: True
ent_coef: 0.01
vf_coef: 0.5
max_grad_norm: 0.5
